import test from "node:test";
import assert from "node:assert/strict";
import {
  buildCompanyListName,
  buildDuplicateListName,
  filterAndSortLists,
  isAutoGeneratedListName,
  resolveListName,
  resolveUpdatedListName
} from "../../shared/orderLists";

test("buildCompanyListName genera l'etichetta strutturata partendo dal nome azienda", () => {
  assert.equal(buildCompanyListName("  Acme Srl  "), "Lista da inviare per Acme Srl");
  assert.equal(buildCompanyListName(""), "");
});

test("isAutoGeneratedListName riconosce etichette auto-generate ignorando maiuscole e spazi", () => {
  assert.equal(
    isAutoGeneratedListName(" lista   da inviare PER acme srl ", "Acme Srl"),
    true
  );
  assert.equal(isAutoGeneratedListName("Lista speciale", "Acme Srl"), false);
});

test("resolveListName e resolveUpdatedListName mantengono il naming corretto", () => {
  assert.equal(resolveListName("Acme Srl"), "Lista da inviare per Acme Srl");
  assert.equal(resolveListName("Acme Srl", " Lista urgente "), "Lista urgente");

  assert.equal(
    resolveUpdatedListName({
      currentName: "Lista da inviare per Acme Srl",
      currentCompanyName: "Acme Srl",
      nextCompanyName: "Beta Spa"
    }),
    "Lista da inviare per Beta Spa"
  );

  assert.equal(
    resolveUpdatedListName({
      currentName: "Lista personalizzata",
      currentCompanyName: "Acme Srl",
      nextCompanyName: "Beta Spa"
    }),
    "Lista personalizzata"
  );
});

test("buildDuplicateListName crea un suffisso progressivo senza collisioni", () => {
  assert.equal(buildDuplicateListName("Lista da inviare per Acme", []), "Lista da inviare per Acme - copia");
  assert.equal(
    buildDuplicateListName("Lista da inviare per Acme", [
      "Lista da inviare per Acme",
      "Lista da inviare per Acme - copia",
      "lista da inviare per acme - copia 2"
    ]),
    "Lista da inviare per Acme - copia 3"
  );
});

test("filterAndSortLists filtra per azienda o nome e ordina correttamente", () => {
  const lists = [
    {
      id: 1,
      name: "Lista da inviare per Gamma",
      company_name: "Gamma",
      created_at: "2026-01-03T08:00:00.000Z",
      updated_at: "2026-01-03T08:00:00.000Z",
      last_accessed_at: "2026-01-03T09:00:00.000Z",
      status: "draft" as const
    },
    {
      id: 2,
      name: "Lista speciale panificio",
      company_name: "Beta",
      created_at: "2026-01-01T08:00:00.000Z",
      updated_at: "2026-01-01T08:00:00.000Z",
      last_accessed_at: "2026-01-01T09:00:00.000Z",
      status: "sent" as const
    },
    {
      id: 3,
      name: "Lista da inviare per Alfa",
      company_name: "Alfa",
      created_at: "2026-01-02T08:00:00.000Z",
      updated_at: "2026-01-02T08:00:00.000Z",
      last_accessed_at: "2026-01-02T09:00:00.000Z",
      status: "received" as const
    }
  ];

  assert.deepEqual(
    filterAndSortLists(lists, "beta", "company-asc").map((item) => item.id),
    [2]
  );

  assert.deepEqual(
    filterAndSortLists(lists, "lista", "name-asc").map((item) => item.id),
    [3, 1, 2]
  );

  assert.deepEqual(
    filterAndSortLists(lists, "", "created-desc").map((item) => item.id),
    [1, 3, 2]
  );
});
