import { FileDown, Minus, Plus, RotateCcw, Send, ShoppingBag, Star, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { Button } from "../components/Button";
import { ProductIcon } from "../components/ProductIcon";
import { SearchBar } from "../components/SearchBar";
import { useAsync } from "../hooks/useAsync";
import { useDebouncedEffect } from "../hooks/useDebouncedEffect";
import { api } from "../services/api";
import type { LastQuantity, Order, Product, Settings } from "../types/domain";
import { formatCurrency, formatDate, orderName } from "../utils/format";
import { buildCompanyListName, isAutoGeneratedListName } from "../../../shared/orderLists";

type QuantityMap = Record<number, { quantity: number; notes: string }>;
type SummaryAction = "pdf" | "xlsx" | "csv" | "whatsapp";

export function OrderBuilder({ settings, editOrderId, clearEditOrder }: { settings: Settings | null; editOrderId?: number | null; clearEditOrder?: () => void }) {
  const { data: products, error: productsError } = useAsync(() => api.products.list(), []);
  const { data: previous, error: previousError } = useAsync(api.orders.previous, []);
  const { data: lastQuantities, error: lastQuantitiesError } = useAsync(api.orders.lastQuantities, []);
  const [companyName, setCompanyName] = useState("");
  const [name, setName] = useState("");
  const [orderId, setOrderId] = useState<number | null>(null);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("");
  const [habitualOnly, setHabitualOnly] = useState(false);
  const [quantities, setQuantities] = useState<QuantityMap>({});
  const [openProduct, setOpenProduct] = useState<Product | null>(null);
  const [summaryAction, setSummaryAction] = useState<SummaryAction | null>(null);
  const [status, setStatus] = useState<Order["status"]>("draft");
  const [saveError, setSaveError] = useState<string | null>(null);
  const [isCustomName, setIsCustomName] = useState(false);
  const lastSavedSignature = useRef("");
  const lastByProduct = useMemo(() => new Map((lastQuantities ?? []).map((item) => [item.product_id, item])), [lastQuantities]);
  const generatedName = useMemo(() => buildCompanyListName(companyName), [companyName]);

  useEffect(() => {
    if (!editOrderId) return;
    api.orders.get(editOrderId).then((order) => {
      setName(order.name);
      setCompanyName(order.company_name);
      setStatus(order.status);
      setIsCustomName(!isAutoGeneratedListName(order.name, order.company_name));
      setOrderId(order.id);
      const nextQuantities = order.items.reduce<QuantityMap>((acc, item) => {
        acc[item.product_id] = { quantity: item.quantity, notes: item.notes ?? "" };
        return acc;
      }, {});
      setQuantities(nextQuantities);
      lastSavedSignature.current = buildDraftSignature({
        companyName: order.company_name,
        name: order.name,
        status: order.status,
        items: buildItemsPayload(nextQuantities)
      });
      clearEditOrder?.();
    }).catch((error) => setSaveError(error instanceof Error ? error.message : "Errore inatteso"));
  }, [editOrderId, clearEditOrder]);

  const visibleProducts = useMemo(() => {
    return (products ?? []).filter((product) => {
      const textMatch = product.name.toLowerCase().includes(query.toLowerCase());
      const categoryMatch = !category || product.category === category;
      const habitMatch = !habitualOnly || product.habitual === 1;
      return textMatch && categoryMatch && habitMatch;
    });
  }, [products, query, category, habitualOnly]);

  const selectedItems = useMemo(() => {
    return (products ?? [])
      .map((product) => {
        const current = quantities[product.id];
        const quantity = current?.quantity ?? 0;
        if (quantity <= 0) return null;

        return {
          ...product,
          quantity,
          notes: current?.notes ?? "",
          lineTotal: Number((quantity * product.price).toFixed(2))
        };
      })
      .filter((item): item is Product & { quantity: number; notes: string; lineTotal: number } => !!item)
      .sort((a, b) => a.name.localeCompare(b.name, "it"));
  }, [products, quantities]);

  const summary = useMemo(() => {
    return selectedItems.reduce(
      (acc, item) => ({
        itemCount: acc.itemCount + 1,
        totalQuantity: Number((acc.totalQuantity + item.quantity).toFixed(2)),
        totalAmount: Number((acc.totalAmount + item.lineTotal).toFixed(2))
      }),
      { itemCount: 0, totalQuantity: 0, totalAmount: 0 }
    );
  }, [selectedItems]);

  function change(productId: number, delta: number) {
    setQuantities((current) => {
      const item = current[productId] ?? { quantity: 0, notes: "" };
      return { ...current, [productId]: { ...item, quantity: Math.max(0, Number((item.quantity + delta).toFixed(2))) } };
    });
  }

  function setQuantity(productId: number, quantity: number) {
    setQuantities((current) => ({ ...current, [productId]: { ...(current[productId] ?? { notes: "" }), quantity } }));
  }

  function setNote(productId: number, notes: string) {
    setQuantities((current) => ({ ...current, [productId]: { ...(current[productId] ?? { quantity: 0 }), notes } }));
  }

  async function share(format: "pdf" | "xlsx" | "csv", targetWindow?: Window | null) {
    const saved = await persistOrder("sent");
    const exportUrl = typeof window === "undefined"
      ? api.exportUrl(saved.id, format)
      : new URL(api.exportUrl(saved.id, format), window.location.origin).toString();
    if (targetWindow) targetWindow.location.href = exportUrl;
    else window.location.assign(exportUrl);
  }

  async function whatsapp(targetWindow?: Window | null) {
    const saved = await persistOrder("sent");
    const lines = selectedItems.map((product) => `${product.name}: ${product.quantity} ${product.unit}`);
    const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(
      `${saved.name}\nAzienda destinataria: ${saved.company_name}\n\n${lines.join("\n")}`
    )}`;
    if (targetWindow) targetWindow.location.href = whatsappUrl;
    else window.location.assign(whatsappUrl);
  }

  function openSummary(action: SummaryAction) {
    if (!companyName.trim()) {
      setSaveError("Inserisci il nome dell'azienda prima di inviare o salvare la lista.");
      return;
    }
    if (!selectedItems.length) {
      setSaveError("Aggiungi almeno un prodotto prima di condividere la lista.");
      return;
    }
    setSummaryAction(action);
  }

  async function confirmSummary(targetWindow?: Window | null) {
    if (!summaryAction) return;
    if (summaryAction === "whatsapp") await whatsapp(targetWindow);
    else await share(summaryAction, targetWindow);
    setSummaryAction(null);
  }

  function handleCompanyChange(value: string) {
    setSaveError(null);
    const previousCompanyName = companyName;
    setCompanyName(value);
    setName((currentName) => {
      const shouldRegenerate = !isCustomName || !currentName.trim() || isAutoGeneratedListName(currentName, previousCompanyName);
      return shouldRegenerate ? buildCompanyListName(value) : currentName;
    });
    if (!isCustomName) {
      setIsCustomName(false);
    }
  }

  function handleNameChange(value: string) {
    setSaveError(null);
    setName(value);
    setIsCustomName(value.trim() !== "" && !isAutoGeneratedListName(value, companyName));
  }

  async function persistOrder(nextStatus: Order["status"]) {
    if (!companyName.trim()) {
      throw new Error("Il nome dell'azienda e obbligatorio");
    }

    const payload = {
      companyName: companyName.trim(),
      name: resolvedListName(name, companyName),
      status: nextStatus,
      items: buildItemsPayload(quantities)
    };

    const signature = buildDraftSignature(payload);
    if (signature === lastSavedSignature.current && orderId) {
      return {
        id: orderId,
        name: payload.name,
        company_name: payload.companyName,
        status: nextStatus
      } as Order;
    }

    try {
      const saved = orderId
        ? await api.orders.update(orderId, payload)
        : await api.orders.create(payload);

      setOrderId(saved.id);
      setName(saved.name);
      setCompanyName(saved.company_name);
      setStatus(saved.status);
      setIsCustomName(!isAutoGeneratedListName(saved.name, saved.company_name));
      setSaveError(null);
      lastSavedSignature.current = buildDraftSignature({
        companyName: saved.company_name,
        name: saved.name,
        status: saved.status,
        items: payload.items
      });
      return saved;
    } catch (error) {
      const message = error instanceof Error ? error.message : "Errore inatteso";
      setSaveError(message);
      throw error;
    }
  }

  useDebouncedEffect(() => {
    if (!companyName.trim()) return;
    const items = buildItemsPayload(quantities);
    const signature = buildDraftSignature({ companyName, name: resolvedListName(name, companyName), status, items });
    if (signature === lastSavedSignature.current) return;
    persistOrder(status).catch(() => {});
  }, [companyName, name, status, quantities, orderId], 550);

  const canShare = !!companyName.trim() && selectedItems.length > 0;

  return (
    <section className="space-y-4">
      {(productsError || previousError || lastQuantitiesError || saveError) && (
        <div className="rounded-lg bg-rose-50 p-3 text-sm font-bold text-rose-900 ring-1 ring-rose-200 dark:bg-rose-950/40 dark:text-rose-100 dark:ring-rose-900">
          Errore: {productsError ?? previousError ?? lastQuantitiesError ?? saveError}
        </div>
      )}
      <header className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0 flex-1">
            <p className="text-sm font-semibold text-leaf">Nuova lista</p>
            <h1 className="text-2xl font-black">Lista per azienda</h1>
            <p className="mt-1 text-sm text-slate-500">Inserisci l&apos;azienda destinataria: il nome completo della lista viene generato automaticamente ma resta modificabile.</p>
          </div>
          <div className={`rounded-full px-3 py-1 text-xs font-bold ${statusTone(status)}`}>
            {statusLabel(status)}
          </div>
        </div>
        <div className="mt-4 grid gap-3 lg:grid-cols-[1.2fr_1.2fr_auto]">
          <label className="space-y-2">
            <span className="text-sm font-semibold text-slate-600 dark:text-slate-300">Azienda destinataria</span>
            <input
              className="h-12 w-full rounded-xl bg-slate-100 px-4 text-base font-semibold outline-none ring-1 ring-transparent transition focus:ring-leaf dark:bg-slate-800"
              placeholder="Nome azienda"
              value={companyName}
              onChange={(event) => handleCompanyChange(event.target.value)}
              required
            />
          </label>
          <label className="space-y-2">
            <span className="text-sm font-semibold text-slate-600 dark:text-slate-300">Etichetta lista</span>
            <input
              className="h-12 w-full rounded-xl bg-slate-100 px-4 text-base font-semibold outline-none ring-1 ring-transparent transition focus:ring-leaf dark:bg-slate-800"
              placeholder={orderName()}
              value={name}
              onChange={(event) => handleNameChange(event.target.value)}
            />
          </label>
          <div className="flex items-end">
            <Button
              variant="muted"
              icon={<RotateCcw size={16} />}
              onClick={() => {
                setName(generatedName);
                setIsCustomName(false);
              }}
              disabled={!companyName.trim()}
              className="w-full lg:w-auto"
            >
              Nome automatico
            </Button>
          </div>
        </div>
        <div className="mt-3 flex flex-wrap items-center gap-2 text-xs font-semibold text-slate-500">
          <span className="rounded-full bg-slate-100 px-3 py-1 dark:bg-slate-800">
            {isCustomName ? "Etichetta personalizzata" : "Etichetta generata automaticamente"}
          </span>
          <span className="rounded-full bg-slate-100 px-3 py-1 dark:bg-slate-800">
            Creata per: {companyName.trim() || "azienda da definire"}
          </span>
          {orderId && <span className="rounded-full bg-slate-100 px-3 py-1 dark:bg-slate-800">ID lista: {orderId}</span>}
        </div>
      </header>

      {!!previous?.length && (
        <div className="rounded-2xl bg-gradient-to-br from-amber-50 to-white p-4 shadow-sm ring-1 ring-amber-200 dark:from-amber-950/50 dark:to-slate-900 dark:ring-amber-900">
          <div className="flex items-center justify-between gap-3">
            <div>
              <p className="text-sm font-semibold uppercase tracking-wide text-amber-700 dark:text-amber-300">Ordine precedente</p>
              <p className="text-lg font-black text-amber-950 dark:text-amber-50">La settimana scorsa hai ordinato questi prodotti</p>
            </div>
            <div className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900 dark:bg-amber-900/60 dark:text-amber-50">
              Tocca per riusare
            </div>
          </div>
          <div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
            {previous.slice(0, 12).map((item) => (
              <button
                key={item.product_id}
                onClick={() => setQuantity(item.product_id, item.quantity)}
                className="tap-target flex min-h-24 items-center gap-3 rounded-xl bg-white px-4 py-3 text-left shadow-sm ring-1 ring-amber-200 transition hover:ring-amber-300 dark:bg-slate-900 dark:ring-amber-900"
              >
                <ProductIcon src={item.icon} name={item.name} className="h-14 w-14 rounded-2xl bg-amber-100 dark:bg-amber-950" imgClassName="h-9 w-9" />
                <div className="min-w-0 flex-1">
                  <p className="truncate text-base font-black text-slate-900 dark:text-white">{item.name}</p>
                  <p className="truncate text-sm font-medium text-slate-500">{item.category} · {item.unit}</p>
                  <p className="mt-1 text-sm font-bold text-amber-700 dark:text-amber-300">Ultima quantita: {item.quantity}</p>
                </div>
              </button>
            ))}
          </div>
        </div>
      )}

      <SearchBar value={query} onChange={setQuery} placeholder="Cerca durante l'ordine" />
      <div className="flex gap-2 overflow-x-auto pb-1 no-scrollbar">
        <FilterButton active={!category} onClick={() => setCategory("")}>Tutte</FilterButton>
        {(settings?.categories ?? []).map((item) => <FilterButton key={item} active={category === item} onClick={() => setCategory(item)}>{item}</FilterButton>)}
        <FilterButton active={habitualOnly} onClick={() => setHabitualOnly(!habitualOnly)}><Star size={15} /> Abituali</FilterButton>
      </div>

      <div className="space-y-2">
        {visibleProducts.map((product) => (
          <ProductRow
            key={product.id}
            product={product}
            value={quantities[product.id]?.quantity ?? 0}
            lineTotal={Number(((quantities[product.id]?.quantity ?? 0) * product.price).toFixed(2))}
            onMinus={() => change(product.id, -1)}
            onPlus={() => change(product.id, 1)}
            onOpen={() => setOpenProduct(product)}
          />
        ))}
      </div>

      <section className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800">
        <div className="flex items-start justify-between gap-3">
          <div>
            <p className="text-sm font-semibold text-leaf">Selezione corrente</p>
            <h2 className="text-xl font-black">Riepilogo rapido ordine</h2>
            <p className="mt-1 text-sm text-slate-500">Lista: {resolvedListName(name, companyName) || "nome lista da definire"} · Azienda: {companyName.trim() || "non impostata"}</p>
          </div>
          <div className="text-right">
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Totale ordine</p>
            <p className="text-2xl font-black text-leaf">{formatCurrency(summary.totalAmount)}</p>
          </div>
        </div>
        <div className="mt-3 grid gap-3 sm:grid-cols-3">
          <SummaryStat label="Prodotti selezionati" value={String(summary.itemCount)} />
          <SummaryStat label="Quantita totale" value={String(summary.totalQuantity)} />
          <SummaryStat label="Media per riga" value={summary.itemCount ? formatCurrency(summary.totalAmount / summary.itemCount) : formatCurrency(0)} />
        </div>
        {!selectedItems.length ? (
          <div className="mt-4 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm font-medium text-slate-500 dark:border-slate-700 dark:bg-slate-950/40 dark:text-slate-400">
            Nessun prodotto selezionato. Aggiungi le quantita per vedere il riepilogo prima della conferma.
          </div>
        ) : (
          <div className="mt-4 space-y-3">
            {selectedItems.map((item) => (
              <div key={item.id} className="flex items-center gap-3 rounded-xl bg-slate-50 px-4 py-3 ring-1 ring-slate-200 dark:bg-slate-950/40 dark:ring-slate-800">
                <ProductIcon src={item.icon} name={item.name} className="h-12 w-12" imgClassName="h-8 w-8" />
                <div className="min-w-0 flex-1">
                  <p className="truncate text-base font-black">{item.name}</p>
                  <p className="truncate text-sm text-slate-500">
                    {item.quantity} {item.unit} · {formatCurrency(item.price)} cad.
                  </p>
                  {!!item.notes && <p className="truncate text-xs font-medium text-slate-400">Nota: {item.notes}</p>}
                </div>
                <div className="text-right">
                  <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Totale riga</p>
                  <p className="text-lg font-black text-slate-900 dark:text-white">{formatCurrency(item.lineTotal)}</p>
                </div>
              </div>
            ))}
          </div>
        )}
      </section>

      <div className="sticky bottom-20 z-20 grid grid-cols-4 gap-2 rounded-lg bg-white p-2 shadow-soft ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-800 lg:bottom-4">
        <Button variant="muted" icon={<FileDown size={18} />} onClick={() => openSummary("pdf")} disabled={!canShare}>PDF</Button>
        <Button variant="muted" onClick={() => openSummary("xlsx")} disabled={!canShare}>Excel</Button>
        <Button variant="muted" onClick={() => openSummary("csv")} disabled={!canShare}>CSV</Button>
        <Button onClick={() => openSummary("whatsapp")} disabled={!canShare}>WhatsApp</Button>
      </div>

      {openProduct && (
        <ProductSheet
          product={openProduct}
          last={lastByProduct.get(openProduct.id)}
          note={quantities[openProduct.id]?.notes ?? ""}
          onNote={(note) => setNote(openProduct.id, note)}
          onUseLast={() => {
            const last = lastByProduct.get(openProduct.id);
            if (last?.last_quantity) setQuantity(openProduct.id, last.last_quantity);
          }}
          onClose={() => setOpenProduct(null)}
        />
      )}

      {summaryAction && (
        <SummaryModal
          orderName={name}
          companyName={companyName}
          status={status}
          action={summaryAction}
          items={selectedItems}
          totalQuantity={summary.totalQuantity}
          totalAmount={summary.totalAmount}
          onClose={() => setSummaryAction(null)}
          onConfirm={confirmSummary}
        />
      )}
    </section>
  );
}

function ProductRow({
  product,
  value,
  lineTotal,
  onMinus,
  onPlus,
  onOpen
}: {
  product: Product;
  value: number;
  lineTotal: number;
  onMinus: () => void;
  onPlus: () => void;
  onOpen: () => void;
}) {
  return (
    <article
      onClick={onOpen}
      className={`grid grid-cols-[52px_1fr_auto] items-center gap-3 rounded-2xl p-3 ring-1 transition ${
        value > 0
          ? "bg-teal-50 ring-teal-200 dark:bg-teal-950/30 dark:ring-teal-900"
          : "bg-white ring-slate-200 dark:bg-slate-900 dark:ring-slate-800"
      }`}
    >
      <ProductIcon src={product.icon} name={product.name} className="h-12 w-12" imgClassName="h-8 w-8" />
      <div className="min-w-0">
        <h3 className="truncate text-base font-black">{product.name}</h3>
        <p className="truncate text-sm font-semibold text-slate-500">{product.category} · {product.unit}</p>
        <div className="mt-1 flex flex-wrap items-center gap-2 text-xs font-bold">
          <span className="rounded-full bg-slate-100 px-2 py-1 text-slate-600 dark:bg-slate-800 dark:text-slate-200">{formatCurrency(product.price)} cad.</span>
          {value > 0 && <span className="rounded-full bg-teal-100 px-2 py-1 text-teal-800 dark:bg-teal-900/70 dark:text-teal-100">Riga: {formatCurrency(lineTotal)}</span>}
        </div>
      </div>
      <div className="flex items-center gap-2">
        <Button variant="muted" icon={<Minus size={18} />} onClick={(e) => { e.stopPropagation(); onMinus(); }} aria-label="Diminuisci" />
        <span className="min-w-14 text-center text-xl font-black tabular-nums">{value}</span>
        <Button icon={<Plus size={18} />} onClick={(e) => { e.stopPropagation(); onPlus(); }} aria-label="Aumenta" />
      </div>
    </article>
  );
}

function ProductSheet({ product, last, note, onNote, onUseLast, onClose }: { product: Product; last?: LastQuantity; note: string; onNote: (value: string) => void; onUseLast: () => void; onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-40 flex items-end bg-slate-950/45 p-3" onClick={onClose}>
      <div className="w-full rounded-lg bg-white p-4 shadow-soft dark:bg-slate-900" onClick={(event) => event.stopPropagation()}>
        <div className="flex items-start gap-3">
          <ProductIcon src={product.icon} name={product.name} className="h-16 w-16 rounded-2xl" imgClassName="h-12 w-12" />
          <div className="min-w-0">
            <h2 className="text-xl font-black">{product.name}</h2>
            <p className="text-sm text-slate-500">{product.category} · {product.unit}</p>
            <p className="text-sm text-slate-500">Ultima quantità: {last?.last_quantity ?? "-"} · {formatDate(last?.last_order_date)}</p>
            <p className="mt-1 text-sm font-bold text-leaf">Prezzo unitario: {formatCurrency(product.price)}</p>
          </div>
        </div>
        <textarea className="mt-3 min-h-28 w-full rounded-lg bg-slate-100 p-3 dark:bg-slate-800" placeholder="Note per questo ordine" value={note} onChange={(event) => onNote(event.target.value)} />
        <div className="mt-3 grid grid-cols-2 gap-2">
          <Button variant="muted" onClick={onClose}>Chiudi</Button>
          <Button onClick={onUseLast}>Usa ultima quantità</Button>
        </div>
      </div>
    </div>
  );
}

function SummaryStat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl bg-slate-50 px-4 py-3 ring-1 ring-slate-200 dark:bg-slate-950/40 dark:ring-slate-800">
      <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p>
      <p className="mt-1 text-2xl font-black text-slate-900 dark:text-white">{value}</p>
    </div>
  );
}

function SummaryModal({
  orderName,
  companyName,
  status,
  action,
  items,
  totalQuantity,
  totalAmount,
  onClose,
  onConfirm
}: {
  orderName: string;
  companyName: string;
  status: Order["status"];
  action: SummaryAction;
  items: Array<Product & { quantity: number; notes: string; lineTotal: number }>;
  totalQuantity: number;
  totalAmount: number;
  onClose: () => void;
  onConfirm: (targetWindow?: Window | null) => void | Promise<void>;
}) {
  const actionLabel = action === "pdf" ? "esporta in PDF" : action === "xlsx" ? "esporta in Excel" : action === "csv" ? "esporta in CSV" : "invia su WhatsApp";

  return (
    <div className="fixed inset-0 z-50 flex items-end bg-slate-950/55 p-3 md:items-center md:justify-center" onClick={onClose}>
      <div className="max-h-[90vh] w-full max-w-4xl overflow-hidden rounded-3xl bg-white shadow-soft dark:bg-slate-900" onClick={(event) => event.stopPropagation()}>
        <div className="flex items-start justify-between gap-4 border-b border-slate-200 px-5 py-4 dark:border-slate-800">
          <div>
            <p className="text-sm font-semibold text-leaf">Riepilogo ordine</p>
            <h2 className="text-2xl font-black">{orderName}</h2>
            <p className="text-sm text-slate-500">Azienda destinataria: {companyName || "non impostata"} · Stato attuale: {statusLabel(status).toLowerCase()}.</p>
            <p className="text-sm text-slate-500">Controlla i prodotti selezionati prima di confermare e {actionLabel}.</p>
          </div>
          <button onClick={onClose} className="rounded-full p-2 text-slate-500 transition hover:bg-slate-100 hover:text-slate-900 dark:hover:bg-slate-800 dark:hover:text-white" aria-label="Chiudi riepilogo">
            <X size={20} />
          </button>
        </div>

        <div className="grid gap-3 border-b border-slate-200 px-5 py-4 dark:border-slate-800 sm:grid-cols-3">
          <SummaryStat label="Prodotti" value={String(items.length)} />
          <SummaryStat label="Quantita totale" value={String(totalQuantity)} />
          <SummaryStat label="Totale complessivo" value={formatCurrency(totalAmount)} />
        </div>

        <div className="max-h-[48vh] overflow-y-auto px-5 py-4">
          <div className="hidden grid-cols-[minmax(0,1.7fr)_110px_140px_150px] gap-3 rounded-xl bg-slate-100 px-4 py-3 text-xs font-bold uppercase tracking-wide text-slate-500 dark:bg-slate-800 dark:text-slate-300 md:grid">
            <span>Prodotto</span>
            <span className="text-right">Quantita</span>
            <span className="text-right">Prezzo unitario</span>
            <span className="text-right">Totale</span>
          </div>
          <div className="mt-3 space-y-3">
            {items.map((item) => (
              <div key={item.id} className="rounded-2xl bg-slate-50 px-4 py-4 ring-1 ring-slate-200 dark:bg-slate-950/40 dark:ring-slate-800">
                <div className="grid gap-3 md:grid-cols-[minmax(0,1.7fr)_110px_140px_150px] md:items-center">
                  <div className="flex items-center gap-3">
                    <ProductIcon src={item.icon} name={item.name} className="h-12 w-12" imgClassName="h-8 w-8" />
                    <div className="min-w-0">
                      <p className="truncate text-base font-black">{item.name}</p>
                      <p className="truncate text-sm text-slate-500">{item.category} · {item.unit}</p>
                      {!!item.notes && <p className="mt-1 text-xs font-medium text-slate-400">Nota: {item.notes}</p>}
                    </div>
                  </div>
                  <div className="text-sm font-bold md:text-right">{item.quantity}</div>
                  <div className="text-sm font-bold md:text-right">{formatCurrency(item.price)}</div>
                  <div className="text-base font-black text-leaf md:text-right">{formatCurrency(item.lineTotal)}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="flex flex-col gap-3 border-t border-slate-200 px-5 py-4 dark:border-slate-800 md:flex-row md:items-center md:justify-between">
          <div className="flex items-center gap-2 text-sm text-slate-500">
            <ShoppingBag size={16} />
            <span>Totale ordine confermato: {formatCurrency(totalAmount)}</span>
          </div>
          <div className="grid grid-cols-2 gap-2 md:flex">
            <Button variant="muted" onClick={onClose}>Torna ai prodotti</Button>
            <Button
              onClick={() => {
                const popup = typeof window === "undefined" ? null : window.open("", "_blank");
                void onConfirm(popup);
              }}
            >
              {action === "whatsapp" ? "Conferma e invia" : "Conferma e continua"}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

function FilterButton({ active, children, onClick }: { active: boolean; children: React.ReactNode; onClick: () => void }) {
  return (
    <button onClick={onClick} className={`tap-target inline-flex shrink-0 items-center gap-1 rounded-lg px-3 text-sm font-bold ${active ? "bg-leaf text-white" : "bg-white text-slate-600 ring-1 ring-slate-200 dark:bg-slate-900 dark:text-slate-200 dark:ring-slate-800"}`}>
      {children}
    </button>
  );
}

function buildItemsPayload(quantities: QuantityMap) {
  return Object.entries(quantities).map(([productId, item]) => ({
    productId: Number(productId),
    quantity: item.quantity,
    notes: item.notes
  }));
}

function buildDraftSignature({
  companyName,
  name,
  status,
  items
}: {
  companyName: string;
  name: string;
  status: Order["status"];
  items: Array<{ productId: number; quantity: number; notes?: string }>;
}) {
  return JSON.stringify({
    companyName: companyName.trim(),
    name: name.trim(),
    status,
    items: items
      .filter((item) => item.quantity > 0 || item.notes?.trim())
      .sort((left, right) => left.productId - right.productId)
  });
}

function resolvedListName(name: string, companyName: string) {
  return name.trim() || buildCompanyListName(companyName) || orderName();
}

function statusLabel(status: Order["status"]) {
  if (status === "received") return "Ricevuta";
  if (status === "sent") return "Inviata";
  return "Bozza";
}

function statusTone(status: Order["status"]) {
  if (status === "received") return "bg-emerald-100 text-emerald-800 dark:bg-emerald-950/60 dark:text-emerald-200";
  if (status === "sent") return "bg-sky-100 text-sky-800 dark:bg-sky-950/60 dark:text-sky-200";
  return "bg-amber-100 text-amber-900 dark:bg-amber-950/60 dark:text-amber-200";
}
