export type ListStatus = "draft" | "sent" | "received";

export type ListSummary = {
  id: number;
  name: string;
  company_name: string;
  created_at: string;
  updated_at: string;
  last_accessed_at?: string | null;
  status: ListStatus;
  item_count?: number;
  total_quantity?: number;
  preview_items?: Array<{
    product_id: number;
    name: string;
    icon?: string;
  }>;
};

export type ListSortKey = "created-desc" | "created-asc" | "company-asc" | "company-desc" | "name-asc" | "name-desc";

export function buildCompanyListName(companyName: string) {
  const normalized = companyName.trim();
  return normalized ? `Lista da inviare per ${normalized}` : "";
}

export function isAutoGeneratedListName(name: string, companyName: string) {
  return normalizeLabel(name) === normalizeLabel(buildCompanyListName(companyName));
}

export function resolveListName(companyName: string, proposedName?: string) {
  const trimmedName = proposedName?.trim();
  return trimmedName || buildCompanyListName(companyName);
}

export function resolveUpdatedListName({
  currentName,
  currentCompanyName,
  nextCompanyName,
  proposedName
}: {
  currentName: string;
  currentCompanyName: string;
  nextCompanyName: string;
  proposedName?: string;
}) {
  const trimmedName = proposedName?.trim();
  if (trimmedName) return trimmedName;
  if (isAutoGeneratedListName(currentName, currentCompanyName)) {
    return buildCompanyListName(nextCompanyName);
  }
  return currentName;
}

export function buildDuplicateListName(name: string, existingNames: string[]) {
  const trimmedName = name.trim();
  const duplicateBase = `${trimmedName} - copia`;
  const normalizedExisting = new Set(existingNames.map((value) => normalizeLabel(value)));
  if (!normalizedExisting.has(normalizeLabel(duplicateBase))) {
    return duplicateBase;
  }

  let suffix = 2;
  while (normalizedExisting.has(normalizeLabel(`${duplicateBase} ${suffix}`))) {
    suffix += 1;
  }

  return `${duplicateBase} ${suffix}`;
}

export function normalizeLabel(value: string) {
  return value.trim().replace(/\s+/g, " ").toLocaleLowerCase("it");
}

export function filterAndSortLists(lists: ListSummary[], search: string, sortBy: ListSortKey) {
  const normalizedSearch = normalizeLabel(search);

  const filtered = !normalizedSearch
    ? [...lists]
    : lists.filter((list) =>
      [list.company_name, list.name]
        .map((value) => normalizeLabel(value))
        .some((value) => value.includes(normalizedSearch))
    );

  return filtered.sort((left, right) => compareLists(left, right, sortBy));
}

function compareLists(left: ListSummary, right: ListSummary, sortBy: ListSortKey) {
  switch (sortBy) {
    case "created-asc":
      return left.created_at.localeCompare(right.created_at);
    case "company-asc":
      return compareText(left.company_name, right.company_name) || compareText(left.name, right.name);
    case "company-desc":
      return compareText(right.company_name, left.company_name) || compareText(right.name, left.name);
    case "name-asc":
      return compareText(left.name, right.name) || compareText(left.company_name, right.company_name);
    case "name-desc":
      return compareText(right.name, left.name) || compareText(right.company_name, left.company_name);
    case "created-desc":
    default:
      return right.created_at.localeCompare(left.created_at);
  }
}

function compareText(left: string, right: string) {
  return left.localeCompare(right, "it", { sensitivity: "base" });
}
