create table if not exists public.products (
  id integer generated by default as identity primary key,
  name text not null unique,
  category text not null,
  unit text not null,
  notes text not null default '',
  habitual boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.orders (
  id integer generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  status text not null default 'draft' check (status in ('draft', 'sent'))
);

create table if not exists public.order_items (
  id integer generated by default as identity primary key,
  order_id integer not null references public.orders(id) on delete cascade,
  product_id integer not null references public.products(id) on delete cascade,
  quantity double precision not null default 0,
  notes text not null default '',
  unique (order_id, product_id)
);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null
);

create index if not exists idx_products_name on public.products (name);
create index if not exists idx_products_category on public.products (category);
create index if not exists idx_orders_created_at on public.orders (created_at desc);
create index if not exists idx_items_order_id on public.order_items (order_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

create or replace function public.reset_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists(select 1 from public.products) then
    perform setval(
      pg_get_serial_sequence('public.products', 'id'),
      (select max(id) from public.products),
      true
    );
  else
    perform setval(
      pg_get_serial_sequence('public.products', 'id'),
      1,
      false
    );
  end if;

  if exists(select 1 from public.orders) then
    perform setval(
      pg_get_serial_sequence('public.orders', 'id'),
      (select max(id) from public.orders),
      true
    );
  else
    perform setval(
      pg_get_serial_sequence('public.orders', 'id'),
      1,
      false
    );
  end if;

  if exists(select 1 from public.order_items) then
    perform setval(
      pg_get_serial_sequence('public.order_items', 'id'),
      (select max(id) from public.order_items),
      true
    );
  else
    perform setval(
      pg_get_serial_sequence('public.order_items', 'id'),
      1,
      false
    );
  end if;
end;
$$;

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.settings enable row level security;

drop policy if exists products_authenticated_read on public.products;
create policy products_authenticated_read on public.products
for select
to authenticated
using (true);

drop policy if exists products_authenticated_write on public.products;
create policy products_authenticated_write on public.products
for all
to authenticated
using (true)
with check (true);

drop policy if exists orders_authenticated_read on public.orders;
create policy orders_authenticated_read on public.orders
for select
to authenticated
using (true);

drop policy if exists orders_authenticated_write on public.orders;
create policy orders_authenticated_write on public.orders
for all
to authenticated
using (true)
with check (true);

drop policy if exists order_items_authenticated_read on public.order_items;
create policy order_items_authenticated_read on public.order_items
for select
to authenticated
using (true);

drop policy if exists order_items_authenticated_write on public.order_items;
create policy order_items_authenticated_write on public.order_items
for all
to authenticated
using (true)
with check (true);

drop policy if exists settings_authenticated_read on public.settings;
create policy settings_authenticated_read on public.settings
for select
to authenticated
using (true);

drop policy if exists settings_authenticated_write on public.settings;
create policy settings_authenticated_write on public.settings
for all
to authenticated
using (true)
with check (true);

insert into public.settings (key, value)
values
  ('businessName', '"Magazzino"'::jsonb),
  ('preferredExport', '"pdf"'::jsonb),
  ('categories', '["Bevande", "Alimentari", "Pulizia", "Monouso", "Altro"]'::jsonb),
  ('units', '["pezzi", "kg", "litri", "confezioni"]'::jsonb),
  ('logo', '""'::jsonb)
on conflict (key) do nothing;
